name: Build domain MRS

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.lst"
      - "scripts/convert.py"
      - ".github/workflows/build-mrs.yml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Download mihomo
        run: |
          echo "Скачивание ядра..."
          wget -O mihomo.gz https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/mihomo-linux-amd64-alpha-24b6de7.gz
          
          echo "Распаковка..."
          gunzip -f mihomo.gz
          chmod +x mihomo
          
          echo "Регистрация в системе..."
          # Копируем в системную директорию, чтобы команда "mihomo" работала глобально
          sudo cp mihomo /usr/local/bin/mihomo
          
          echo "Проверка версии ядра:"
          mihomo -v

      - name: Build MRS from LST
        run: |
          python3 scripts/convert.py

      - name: Commit generated MRS files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@://github.com"

          # Добавляем все новые и измененные .mrs файлы
          find . -type f -name "*.mrs" -print0 | xargs -0 git add

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Auto-build .mrs from .lst [skip ci]"
          git push
